# Documentation about this file can be found in this file: `docs/install/1-CONFIG.md`

security:
  disabled: true
  jwt:
    key: super-secret

db:
  url: "sqlite:///database.db"

storage:
  tmp_dir: /home/milos/Documents/RTEi/03-Antares-Web/01-SourceCode/antares_data/tmp
  matrixstore: /home/milos/Documents/RTEi/03-Antares-Web/01-SourceCode/antares_data/matrices
  archive_dir: /home/milos/Documents/RTEi/03-Antares-Web/01-SourceCode/antares_data/archives
  workspaces:
    default:
      path: /home/milos/Documents/RTEi/03-Antares-Web/01-SourceCode/antares_data/internal_studies/
    studies:
      path: /home/milos/Documents/RTEi/03-Antares-Web/01-SourceCode/antares_data/studies/

launcher:
  default: local

  local:
    binaries:
      880: /home/milos/Documents/RTEi/03-Antares-Web/01-SourceCode/antares_data/solver/test-new-input/antares-8.8-solver
    enable_nb_cores_detection: true

# See https://fastapi.tiangolo.com/advanced/behind-a-proxy/
# root path is used when the API is served behind a proxy which
# adds a prefix for clients.
# It does NOT add any prefix to the URLs which fastapi serve.

# root_path: "api"


# Uncomment to serve the API under /api prefix
# (used in standalone mode to emulate the effect of proxy servers
# used in production deployments).

api_prefix: "/api"

# api_prefix: Typically used in the FastAPI app code to define the actual base path of your routes (e.g., /api).

server:
  worker_threadpool_size: 12
  services:
    - watcher
    - matrix_gc

logging:
  level: INFO
  logfile: /home/milos/Documents/RTEi/03-Antares-Web/01-SourceCode/antares_data/logs/antarest.log

# True to get sqlalchemy logs
debug: False
