# Documentation about this file can be found in this file: `docs/install/1-CONFIG.md`

security:
  disabled: true
  jwt:
    key: super-secret

db:
  url: "sqlite:///database.db"

storage:
  tmp_dir: /home/milos/Documents/RTEi/03-Antares-Web/01-SourceCode/antares_data/tmp
  matrixstore: /home/milos/Documents/RTEi/03-Antares-Web/01-SourceCode/antares_data/matrices
  archive_dir: /home/milos/Documents/RTEi/03-Antares-Web/01-SourceCode/antares_data/archives
  workspaces:
    default:
      path: /home/milos/Documents/RTEi/03-Antares-Web/01-SourceCode/antares_data/internal_studies/
    studies:
      path: /home/milos/Documents/RTEi/03-Antares-Web/01-SourceCode/antares_data/studies/

launcher:
  local:
    binaries:
      880: /home/milos/Documents/RTEi/03-Antares-Web/01-SourceCode/antares_data/solver/test-new-input/antares-8.8-solver

#  slurm:
#    local_workspace: /path/to/slurm_workspace  # Path to the local SLURM workspace
#    username: run-antares  # SLURM username
#    hostname: 10.134.248.111  # SLURM server hostname
#    port: 22  # SSH port for SLURM
#    private_key_file: /path/to/ssh_private_key  # SSH private key file
#    default_wait_time: 900  # Default wait time for SLURM jobs
#    default_time_limit: 172800  # Default time limit for SLURM jobs
#    enable_nb_cores_detection: False  # Enable detection of available CPU cores for SLURM
#    nb_cores:
#      min: 1  # Minimum number of CPU cores
#      default: 22  # Default number of CPU cores
#      max: 24  # Maximum number of CPU cores
#    default_json_db_name: launcher_db.json  # Default JSON database name for SLURM
#    slurm_script_path: /applis/antares/launchAntares.sh  # Path to the SLURM script (on distant server)
#    db_primary_key: name  # Primary key for the SLURM database
#    antares_versions_on_remote_server: #List of Antares versions available on the remote SLURM server
#      - "840"
#      - "850"


debug: false

# Serve the API at /api
api_prefix: "/api"

# api_prefix: Typically used in the FastAPI app code to define the actual base path of your routes (e.g., /api).

server:
  worker_threadpool_size: 12
  services:
    - watcher

logging:
  logfile: /home/milos/Documents/RTEi/03-Antares-Web/01-SourceCode/antares_data/logs/antarest.log